package p3project.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import p3project.classes.User;

// This will be AUTO IMPLEMENTED by Spring into a Bean called userRepository
// CRUD refers Create, Read, Update, Delete

public interface UserRepository extends JpaRepository<User, Integer> {
	// Automatically generated by Spring
	User findByName(String name);
}



// Spring creates these methods:
// userRepository.save(user);           // INSERT/UPDATE
// userRepository.findAll();            // SELECT * FROM user
// userRepository.findById(1);          // SELECT * FROM user WHERE id=1
// userRepository.deleteById(1);        // DELETE FROM user WHERE id=1
// userRepository.count();              // SELECT COUNT(*) FROM user