package p3project;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDate;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.*;

import p3project.classes.Contract;
import p3project.classes.Sponsor;
import p3project.classes.User;
import p3project.repositories.ContractRepository;
import p3project.repositories.SponsorRepository;
import p3project.classes.Eventlog;
import p3project.classes.Changelog;
import p3project.repositories.UserRepository;
import p3project.repositories.LogRepository;


import java.lang.reflect.Field;

import static p3project.classes.Action.*;

@Controller	// This means that this class is a Controller
public class MainController {
	@Autowired // This means to get the bean called userRepository, auto-generated by Spring, used to handle the data
	private UserRepository userRepository;
    @Autowired
    private LogRepository logRepository;

	@Autowired
	private ContractRepository contractRepository;
	
	@Autowired
	private SponsorRepository sponsorRepository;

	// API endpoints (JSON responses)
	@PostMapping(path="/demo/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/demo/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	// Web page endpoints (HTML responses)
	@GetMapping("/")
	public String home() {
		return "redirect:/users";
	}

	@GetMapping("/users")
	public String showUsers(Model model) { // Model is a container to pass data to the HTML view
		model.addAttribute("users", userRepository.findAll());
		return "users";
	}

	@GetMapping("/test")
	public String showTestPage() {
		return "test";
	}

	@GetMapping("/homepage")
	public String showHomePage() {
		return "homepage";
	}

	@GetMapping("/archive")
	public String showArchivePage() {
		return "archive";
	}

	@GetMapping("/AdminPanel")
	public String showAdminPanelPage() {
		return "AdminPanel";
	}

	@GetMapping("/homepage")
	public String showHomepage(Model model) {
		Iterable<Sponsor> sponsors = sponsorRepository.findAll();
		sponsors.forEach(s -> System.out.println("Sponsor: " + s.getSponsorName()));
		model.addAttribute("sponsors", sponsors);
		return "homepage";
	}

	@PostMapping("/uploadFile")
	public String uploadFileTo(@RequestParam MultipartFile pdffile){
			Contract contact = new Contract(
			LocalDate.of(2025, 1, 1),
			LocalDate.of(2025, 12, 31),
			2000,
			true,
			"Standard"   
		);
		try {
			contact.setPdfData(pdffile.getBytes());
			System.out.println("\n \n PDF file loaded successfully! \n \n");
		} catch (IOException e) {
			e.printStackTrace();
			return "error"; // Or handle appropriately
		}
		

		return "redirect:/users";

	}



    // boilerplate, kombiner på nogen måde?
    @PutMapping("/update/sponsor")
    public String updateSponsorFields(@RequestParam Sponsor sponsor) {
        Sponsor storedSponsor = sponsorRepository.findById(sponsor.getId());
        try {
            compareFields(sponsor, storedSponsor);
        } catch (ClassNotFoundException e) {
            return "Error"; // wip
        }
        return "Success"; // wip
    }

    @PutMapping("/update/contract")
    public String updateContractFields(@RequestParam Contract contract) {
        Contract storedContract = contractRepository.findById(contract.getId());
        try {
            compareFields(contract, storedContract);
        } catch (ClassNotFoundException e) {
            return "Error"; // wip
        }
        return "Success"; // wip
    }

    @PutMapping("/update/service")
    public String updateServiceFields(@RequestParam Service service) {
        Service storedService = serviceRepository.findById(service.getId());
        try {
            compareFields(service, storedService);
        } catch (ClassNotFoundException e) {
            return "Error"; // wip
        }
        return "Success"; // wip
    }

    private <T> void compareFields(T requestObject, T storedObject) throws ClassNotFoundException{ // fjern generic?
        Field[] fields = requestObject.getClass().getDeclaredFields(); // burde være lige meget hvilken en + ingen inheritence, igen lige meget (for nu)
        for(Field field : fields) {
            field.setAccessible(true); // adgang til private
            try {
                Object before = field.get(storedObject); // old, stored...?
                Object after = field.get(requestObject); // new, current...?
                if(!before.equals(after)) {
                    Changelog log = Changelog.create(user, requestObject, requestObject.getName(), before, after); // getName fix?
                    logRepository.save(log);
                    field.set(storedObject, after);
                }
            } catch (IllegalAccessException e) { // skal være der for field.get kan bruges, burde ikke aktivere: setAccessible(true)
                throw new RuntimeException(e);
            }
        }

        if      (requestObject instanceof Sponsor)   sponsorRepository.save(storedObject); // opdater i stedet for gem??
        else if (requestObject instanceof Contract)  contractRepository.save(storedObject);
        else if (requestObject instanceof Service)   serviceRepository.save(storedObject);
        else throw new ClassNotFoundException();
    }


    // Changelog page request (HTML)
    @GetMapping("/changelog")
    public String changelogPage(Model page) {
        page.addAttribute("changelog", logRepository.findAll()); // måske lave noget med sider / dynamisk?
        return "changelog"; // side
    }

	// Missing validation, error handling (try-catch), and security measures
	@PostMapping("/users/add")
	public String addUserFromWeb(@RequestParam String name, @RequestParam String email) {

		Contract contact = new Contract(
			LocalDate.of(2025, 1, 1),
			LocalDate.of(2025, 12, 31),
			2000,
			true,
			"Standard"   
		);

		Sponsor sponsor = new Sponsor(
			"Demo",
			"DemoName", 
			"Demo Email", 
			"12345678", 
			"12345678", 
			false, 
			"Demo Comment");

		sponsorRepository.save(sponsor);

		try {
			byte[] pdfBytes = Files.readAllBytes(Paths.get("C:\\Users\\mathi\\Downloads\\easyFIle.pdf"));
			contact.setPdfData(pdfBytes);
			
			System.out.println("\n \n PDF file loaded successfully! \n \n");
		}catch(Exception e){
			System.out.println("Could not set PDF data: " + e.getMessage());
		}
		contractRepository.save(contact);
		User user = new User();
		user.setName(name);
		user.setEmail(email);
		userRepository.save(user);
		return "redirect:/users";
	}

}