package p3project;

import java.io.IOException;
import java.lang.reflect.Field;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDate;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartFile;

import p3project.classes.Changelog;
import p3project.classes.Contract;
import p3project.classes.Service;
import p3project.classes.Sponsor;
import p3project.classes.User;
import p3project.repositories.ContractRepository;
import p3project.repositories.LogRepository;
import p3project.repositories.ServiceRepository;
import p3project.repositories.SponsorRepository;
import p3project.repositories.UserRepository;

@Controller // This means that this class is a Controller
public class MainController {
    @Autowired // This means to get the bean called userRepository, auto-generated by Spring,
    // used to handle the data
    private UserRepository userRepository;
    @Autowired
    private LogRepository logRepository;

    @Autowired
    private ContractRepository contractRepository;

    @Autowired
    private SponsorRepository sponsorRepository;

    @Autowired
    private ServiceRepository serviceRepository;

		if (!isValidUsername(name)) {
			return "Error: invalid username - only letters, numbers and underscore allowed";
		}

		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/demo/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    // Web page endpoints (HTML responses)
    @GetMapping("/")
    public String home() {
        return "redirect:/users";
    }

    @GetMapping("/users")
    public String showUsers(Model model) { // Model is a container to pass data to the HTML view
        model.addAttribute("users", userRepository.findAll());
        return "users";
    }



    // boilerplate, kombiner på nogen måde?
    @PutMapping("/update/sponsor")
    public @ResponseBody ResponseEntity<String> updateSponsorFields(@RequestBody Sponsor sponsor) {
        Sponsor storedSponsor = sponsorRepository.getReferenceById(sponsor.getId());
        // alt herunder i handleren skal, om muligt, laves til en funktion: return handleRequest(object, storedObject)... typ skit
        Integer fieldsChanged;
        try {
            fieldsChanged = compareFields(sponsor, storedSponsor);
        } catch (ClassNotFoundException e) {
            return new ResponseEntity<>("Internal server error", HttpStatus.INTERNAL_SERVER_ERROR);
        }
        return new ResponseEntity<>(fieldsChanged.toString(), HttpStatus.OK);
    }

    @PutMapping("/update/contract")
    public @ResponseBody ResponseEntity<String> updateContractFields(@RequestBody Contract contract) {
        Contract storedContract = contractRepository.getReferenceById(contract.getId());
        Integer fieldsChanged;
        try {
            fieldsChanged = compareFields(contract, storedContract);
        } catch (ClassNotFoundException e) {
            return new ResponseEntity<>("Internal server error", HttpStatus.INTERNAL_SERVER_ERROR);
        }
        return new ResponseEntity<>(fieldsChanged.toString(), HttpStatus.OK);
    }

    @PutMapping("/update/service")
    public @ResponseBody ResponseEntity<String> updateServiceFields(@RequestBody Service service) {
        Service storedService = serviceRepository.getReferenceById(service.getId());
        Integer fieldsChanged;
        try {
            fieldsChanged = compareFields(service, storedService);
        } catch (ClassNotFoundException e) {
            return new ResponseEntity<>("Internal server error", HttpStatus.INTERNAL_SERVER_ERROR);
        }
        return new ResponseEntity<>(fieldsChanged.toString(), HttpStatus.OK);
    }

    // returnér int med antal af opdaterede felter(?)
    private <T> Integer compareFields(T requestObject, T storedObject) throws ClassNotFoundException{ // fjern generic
        Integer fieldsChanged = 0;
        Field[] fields = requestObject.getClass().getDeclaredFields(); // burde være lige meget hvilken en + ingen inheritence, igen lige meget (for nu)
        for(Field field : fields) {
            field.setAccessible(true); // adgang til private
            try {
                if(field.getName().equals("id")) continue;
                Object before = field.get(storedObject); // old, stored...?
                Object after = field.get(requestObject); // new, current...?
                if(!before.equals(after)) {
                    User user = new User(); // <-- skal slettes
                    Changelog log = Changelog.create(user, requestObject.toString(), requestObject.toString(), before.toString(), after.toString()); // wip
                    logRepository.save(log);
                    field.set(storedObject, after);
                    fieldsChanged++;
                    System.out.println("Updated " + field.toString() + ": " + before.toString() + " -> " + after.toString());
                }
            } catch (IllegalAccessException error) { // skal være der for field.get kan bruges, burde ikke aktivere: setAccessible(true)
                throw new RuntimeException(error);
            }
        }

        if (requestObject instanceof Sponsor)       sponsorRepository.save((Sponsor)storedObject); // opdater i stedet for gem??
        else if (requestObject instanceof Contract) contractRepository.save((Contract)storedObject);
        else if (requestObject instanceof Service)  serviceRepository.save((Service)storedObject);
        else throw new ClassNotFoundException();
        
        return fieldsChanged;
    }


	// Displays the sponsors page with lists of sponsors and contracts
	@GetMapping("/sponsors")
	public String showSponsors(Model model) {
		model.addAttribute("sponsors", sponsorRepository.findAll());
		model.addAttribute("contracts", contractRepository.findAll());
		return "sponsors";
	}

	// Handles adding a new sponsor from the web form
	@PostMapping("/sponsors/add")
	public String addSponsorFromWeb(
			@RequestParam String sponsorName,
			@RequestParam String contactPerson,
			@RequestParam String email,
			@RequestParam String phoneNumber,
			@RequestParam String cvrNumber,
			@RequestParam(required = false, defaultValue = "false") boolean status,
			@RequestParam(required = false) String comments,
			Model model
	) {
		// Serverside phone validation: kun digits allowed
		if (phoneNumber != null && phoneNumber.length() > 0 && !phoneNumber.matches("^[0-9]+$")) {
			model.addAttribute("error", "Phone number must contain digits only.");
			model.addAttribute("sponsors", sponsorRepository.findAll());
			model.addAttribute("contracts", contractRepository.findAll());
			return "sponsors";
		}

		// Create and save the new sponsor
		Sponsor sponsor = new Sponsor(sponsorName, contactPerson, email, phoneNumber, cvrNumber, status, comments == null ? "" : comments);
		sponsorRepository.save(sponsor);
		return "redirect:/sponsors";
	}

	// Handles creating a new contract for a sponsor
	@PostMapping("/sponsors/addContract")
	public String addContractForSponsor(
			@RequestParam String sponsorName,
			@RequestParam String startDate,
			@RequestParam String endDate,
			@RequestParam int payment,
			@RequestParam(required = false, defaultValue = "false") boolean status,
			@RequestParam String type
	) {
		// Parse date strings to LocalDate and save the contract
		LocalDate start = LocalDate.parse(startDate);
		LocalDate end = LocalDate.parse(endDate);
		Contract contract = new Contract(start, end, payment, status, type);
		contract.setSponsorName(sponsorName);
		contractRepository.save(contract);
		return "redirect:/sponsors";
	}

	// Handles editing an existing sponsor
	@PostMapping("/sponsors/edit")
	public String editSponsor(
			@RequestParam String originalSponsorName,
			@RequestParam String sponsorName,
			@RequestParam(required = false) String contactPerson,
			@RequestParam(required = false) String email,
			@RequestParam(required = false) String phoneNumber,
			@RequestParam(required = false) String cvrNumber,
			@RequestParam(required = false, defaultValue = "false") boolean status,
			@RequestParam(required = false) String comments,
			Model model
	) {
		// Validate phone number
		if (phoneNumber != null && phoneNumber.length() > 0 && !phoneNumber.matches("^[0-9]+$")) {
			model.addAttribute("error", "Phone number must contain digits only.");
			model.addAttribute("sponsors", sponsorRepository.findAll());
			model.addAttribute("contracts", contractRepository.findAll());
			return "sponsors";
		}
		// Find sponsor by name
		var maybe = sponsorRepository.findById(originalSponsorName);
		if (maybe.isPresent()) {
			Sponsor s = maybe.get();
			// If the sponsors name (primary key) changes, delete old and create new
			if (!originalSponsorName.equals(sponsorName)) {
				Sponsor newS = new Sponsor(sponsorName,
						contactPerson == null ? s.getContactPerson() : contactPerson,
						email == null ? s.getEmail() : email,
						phoneNumber == null ? s.getPhoneNumber() : phoneNumber,
						cvrNumber == null ? s.getCvrNumber() : cvrNumber,
						status,
						comments == null ? s.getComments() : comments);
				
				// Replace old record
				sponsorRepository.deleteById(originalSponsorName);
				sponsorRepository.save(newS);

				// update contracts to new sponsorName
				Iterable<Contract> contracts = contractRepository.findAll();
				for (Contract c : contracts) {
					if (originalSponsorName.equals(c.getSponsorName())) {
						c.setSponsorName(sponsorName);
						contractRepository.save(c);
					}
				}
			} else {
				// update fields on the same entity
				s.setContactPerson(contactPerson == null ? s.getContactPerson() : contactPerson);
				s.setEmail(email == null ? s.getEmail() : email);
				s.setPhoneNumber(phoneNumber == null ? s.getPhoneNumber() : phoneNumber);
				s.setCvrNumber(cvrNumber == null ? s.getCvrNumber() : cvrNumber);
				s.setStatus(status);
				s.setComments(comments == null ? s.getComments() : comments);
				sponsorRepository.save(s);
			}
		}
		return "redirect:/sponsors";
	}

	// Deletes a sponsor and all contracts linked to that sponsor
	@PostMapping("/sponsors/delete")
	public String deleteSponsor(@RequestParam String sponsorName) {
		// delete sponsor 
		sponsorRepository.deleteById(sponsorName);
		// and related contracts
		Iterable<Contract> contracts = contractRepository.findAll();
		for (Contract c : contracts) {
			if (sponsorName.equals(c.getSponsorName())) {
				contractRepository.deleteById(c.getId());
			}
		}
		return "redirect:/sponsors";
	}

	// Handles editing an existing contract
	@PostMapping("/sponsors/editContract")
	public String editContract(
			@RequestParam Long contractId,
			@RequestParam String sponsorName,
			@RequestParam String startDate,
			@RequestParam String endDate,
			@RequestParam int payment,
			@RequestParam(required = false, defaultValue = "false") boolean status,
			@RequestParam String type
	) {
		var maybe = contractRepository.findById(contractId);
		if (maybe.isPresent()) {
			Contract c = maybe.get();
			// Update contract fields
			c.setSponsorName(sponsorName);
			c.setStartDate(LocalDate.parse(startDate));
			c.setEndDate(LocalDate.parse(endDate));
			c.setPayment(payment);
			c.setStatus(status);
			c.setType(type);
			contractRepository.save(c);
		}
		return "redirect:/sponsors";
	}

	// Deletes a contract by ID
	@PostMapping("/sponsors/deleteContract")
	public String deleteContract(@RequestParam Long contractId) {
		contractRepository.deleteById(contractId);
		return "redirect:/sponsors";
	}

	@PostMapping("/uploadFile")
	public String uploadFileTo(@RequestParam MultipartFile pdffile) {
		Contract contact = new Contract(
				LocalDate.of(2025, 1, 1),
				LocalDate.of(2025, 12, 31),
				2000,
				true,
				"Standard");
		try {
			contact.setPdfData(pdffile.getBytes());
			System.out.println("\n \n PDF file loaded successfully! \n \n");
		} catch (IOException e) {
			e.printStackTrace();
			return "error"; // Or handle appropriately
		}
    // Changelog page request (HTML)
    @GetMapping("/changelog")
    public String changelogPage(Model page) {
        page.addAttribute("changelog", logRepository.findAll()); // måske lave noget med sider / dynamisk?
        return "changelog"; // side (eksisterer ikke endnu)
    }

    @GetMapping("/test")
    public String showTestPage() {
        return "test";
    }

    @GetMapping("/archive")
    public String showArchivePage() {
        return "archive";
    }

    @GetMapping("/AdminPanel")
    public String showAdminPanelPage() {
        return "AdminPanel";
    }

	// Missing validation, error handling (try-catch), and security measures
	@PostMapping("/users/add")
	public String addUserFromWeb(@RequestParam String name, @RequestParam String email, Model model) {
    @GetMapping("/login")
    public String showLoginPage() {
        return "login";
    }

    @GetMapping("/Loginpage3")
    public String showLoginPage3() {
        return "Loginpage3";
    }

    @GetMapping("/Complete")
    public String showCompletePage() {
        return "Complete";
    }

    @GetMapping("/homepage")
    public String showHomepage(Model model) {
        Iterable<Sponsor> sponsors = sponsorRepository.findAll();
        sponsors.forEach(s -> System.out.println("Sponsor: " + s.getSponsorName()));
        model.addAttribute("sponsors", sponsors);
        return "homepage";
    }

    @PostMapping("/uploadFile")
    public String uploadFileTo(@RequestParam MultipartFile pdffile) {
        Contract contact = new Contract(
                LocalDate.of(2025, 1, 1),
                LocalDate.of(2025, 12, 31),
                2000,
                true,
                "Standard");
        try {
            contact.setPdfData(pdffile.getBytes());
            System.out.println("\n \n PDF file loaded successfully! \n \n");
        } catch (IOException e) {
            e.printStackTrace();
            return "error"; // Or handle appropriately
        }

			System.out.println("\n \n PDF file loaded successfully! \n \n");
		} catch (Exception e) {
			System.out.println("Could not set PDF data: " + e.getMessage());
		}
		contractRepository.save(contact);
		if (!isValidUsername(name)) {
			model.addAttribute("error", "Invalid username: only letters, numbers and underscore allowed");
			model.addAttribute("users", userRepository.findAll());
			return "users";
		}

		User user = new User();
		user.setName(name);
		user.setEmail(email);
		userRepository.save(user);
		return "redirect:/users";
	}
        contractRepository.save(contact);

        return "redirect:/users";

		if (!isValidUsername(username)) {
			model.addAttribute("error", "Invalid username: only letters, numbers and underscore allowed");
			return "login";
		}

		User user = userRepository.findByName(username);
    }

    // Missing validation, error handling (try-catch), and security measures
    @PostMapping("/users/add")
    public String addUserFromWeb(@RequestParam String name, @RequestParam String email) {

		model.addAttribute("user", user);
		return "Complete";
	}

	// Username validation: allow only letters, digits and underscore
	private boolean isValidUsername(String username) {
		if (username == null) return false;
		String trimmed = username.trim();
		return trimmed.matches("^[A-Za-z0-9_]+$");
	}
        Contract contact = new Contract(
                LocalDate.of(2025, 1, 1),
                LocalDate.of(2025, 12, 31),
                2000,
                true,
                "Standard");

        Sponsor sponsor = new Sponsor(
                "Demo",
                "DemoName",
                "Demo Email",
                "12345678",
                "12345678",
                false,
                "Demo Comment");

        sponsorRepository.save(sponsor);

        try {
            byte[] pdfBytes = Files.readAllBytes(Paths.get("C:\\Users\\mathi\\Downloads\\easyFIle.pdf"));
            contact.setPdfData(pdfBytes);

            System.out.println("\n \n PDF file loaded successfully! \n \n");
        } catch (Exception e) {
            System.out.println("Could not set PDF data: " + e.getMessage());
        }
        contractRepository.save(contact);
        User user = new User();
        user.setName(name);
        user.setEmail(email);
        userRepository.save(user);
        return "redirect:/users";
    }

    @PostMapping("/login/confirm")
    public String confirmLogin(
            @RequestParam String username,
            @RequestParam String email,
            Model model) {

        User user = userRepository.findByName(username);

        if (user == null || !user.getEmail().equals(email)) {
            model.addAttribute("error", "Invalid username or email");
            return "login";
        }

        model.addAttribute("user", user);
        return "Complete";
    }
}