package p3project;

import java.io.IOException;
import java.lang.reflect.Field;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDate;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartFile;

import p3project.classes.Changelog;
import p3project.classes.Contract;
import p3project.classes.Service;
import p3project.classes.Sponsor;
import p3project.classes.User;
import p3project.repositories.ContractRepository;
import p3project.repositories.LogRepository;
import p3project.repositories.ServiceRepository;
import p3project.repositories.SponsorRepository;
import p3project.repositories.UserRepository;

@Controller // This means that this class is a Controller
public class MainController {
    @Autowired // This means to get the bean called userRepository, auto-generated by Spring,
    // used to handle the data
    private UserRepository userRepository;
    @Autowired
    private LogRepository logRepository;

    @Autowired
    private ContractRepository contractRepository;

    @Autowired
    private SponsorRepository sponsorRepository;

    @Autowired
    private ServiceRepository serviceRepository;

    // API endpoints (JSON responses)
    @PostMapping(path = "/demo/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/demo/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    // Web page endpoints (HTML responses)
    @GetMapping("/")
    public String home() {
        return "redirect:/users";
    }

    @GetMapping("/users")
    public String showUsers(Model model) { // Model is a container to pass data to the HTML view
        model.addAttribute("users", userRepository.findAll());
        return "users";
    }



    // boilerplate, kombiner på nogen måde?
    @PutMapping("/update/sponsor")
    public @ResponseBody ResponseEntity<String> updateSponsorFields(@RequestBody Sponsor sponsor) {
        Sponsor storedSponsor = sponsorRepository.getReferenceById(sponsor.getId());
        // alt herunder i handleren skal, om muligt, laves til en funktion: return handleRequest(object, storedObject)... typ skit
        Integer fieldsChanged;
        try {
            fieldsChanged = compareFields(sponsor, storedSponsor);
        } catch (ClassNotFoundException e) {
            return new ResponseEntity<>("Internal server error", HttpStatus.INTERNAL_SERVER_ERROR);
        }
        return new ResponseEntity<>(fieldsChanged.toString(), HttpStatus.OK);
    }

    @PutMapping("/update/contract")
    public @ResponseBody ResponseEntity<String> updateContractFields(@RequestBody Contract contract) {
        Contract storedContract = contractRepository.getReferenceById(contract.getId());
        Integer fieldsChanged;
        try {
            fieldsChanged = compareFields(contract, storedContract);
        } catch (ClassNotFoundException e) {
            return new ResponseEntity<>("Internal server error", HttpStatus.INTERNAL_SERVER_ERROR);
        }
        return new ResponseEntity<>(fieldsChanged.toString(), HttpStatus.OK);
    }

    @PutMapping("/update/service")
    public @ResponseBody ResponseEntity<String> updateServiceFields(@RequestBody Service service) {
        Service storedService = serviceRepository.getReferenceById(service.getId());
        Integer fieldsChanged;
        try {
            fieldsChanged = compareFields(service, storedService);
        } catch (ClassNotFoundException e) {
            return new ResponseEntity<>("Internal server error", HttpStatus.INTERNAL_SERVER_ERROR);
        }
        return new ResponseEntity<>(fieldsChanged.toString(), HttpStatus.OK);
    }

    // returnér int med antal af opdaterede felter(?)
    private <T> Integer compareFields(T requestObject, T storedObject) throws ClassNotFoundException{ // fjern generic
        Integer fieldsChanged = 0;
        Field[] fields = requestObject.getClass().getDeclaredFields(); // burde være lige meget hvilken en + ingen inheritence, igen lige meget (for nu)
        for(Field field : fields) {
            field.setAccessible(true); // adgang til private
            try {
                if(field.getName().equals("id")) continue;
                Object before = field.get(storedObject); // old, stored...?
                Object after = field.get(requestObject); // new, current...?
                if(!before.equals(after)) {
                    User user = new User(); // <-- skal slettes
                    Changelog log = Changelog.create(user, requestObject.toString(), requestObject.toString(), before.toString(), after.toString()); // wip
                    logRepository.save(log);
                    field.set(storedObject, after);
                    fieldsChanged++;
                    System.out.println("Updated " + field.toString() + ": " + before.toString() + " -> " + after.toString());
                }
            } catch (IllegalAccessException error) { // skal være der for field.get kan bruges, burde ikke aktivere: setAccessible(true)
                throw new RuntimeException(error);
            }
        }

        if (requestObject instanceof Sponsor)       sponsorRepository.save((Sponsor)storedObject); // opdater i stedet for gem??
        else if (requestObject instanceof Contract) contractRepository.save((Contract)storedObject);
        else if (requestObject instanceof Service)  serviceRepository.save((Service)storedObject);
        else throw new ClassNotFoundException();
        
        return fieldsChanged;
    }


    // Changelog page request (HTML)
    @GetMapping("/changelog")
    public String changelogPage(Model page) {
        page.addAttribute("changelog", logRepository.findAll()); // måske lave noget med sider / dynamisk?
        return "changelog"; // side (eksisterer ikke endnu)
    }

    @GetMapping("/test")
    public String showTestPage() {
        return "test";
    }

    @GetMapping("/archive")
    public String showArchivePage() {
        return "archive";
    }

    @GetMapping("/AdminPanel")
    public String showAdminPanelPage() {
        return "AdminPanel";
    }

    @GetMapping("/login")
    public String showLoginPage() {
        return "login";
    }

    @GetMapping("/Loginpage3")
    public String showLoginPage3() {
        return "Loginpage3";
    }

    @GetMapping("/Complete")
    public String showCompletePage() {
        return "Complete";
    }

    @GetMapping("/homepage")
    public String showHomepage(Model model) {
        Iterable<Sponsor> sponsors = sponsorRepository.findAll();
        sponsors.forEach(s -> System.out.println("Sponsor: " + s.getSponsorName()));
        model.addAttribute("sponsors", sponsors);
        return "homepage";
    }

    @PostMapping("/uploadFile")
    public String uploadFileTo(@RequestParam MultipartFile pdffile) {
        Contract contact = new Contract(
                LocalDate.of(2025, 1, 1),
                LocalDate.of(2025, 12, 31),
                2000,
                true,
                "Standard");
        try {
            contact.setPdfData(pdffile.getBytes());
            System.out.println("\n \n PDF file loaded successfully! \n \n");
        } catch (IOException e) {
            e.printStackTrace();
            return "error"; // Or handle appropriately
        }

        contractRepository.save(contact);

        return "redirect:/users";

    }

    // Missing validation, error handling (try-catch), and security measures
    @PostMapping("/users/add")
    public String addUserFromWeb(@RequestParam String name, @RequestParam String email) {

        Contract contact = new Contract(
                LocalDate.of(2025, 1, 1),
                LocalDate.of(2025, 12, 31),
                2000,
                true,
                "Standard");

        Sponsor sponsor = new Sponsor(
                "Demo",
                "DemoName",
                "Demo Email",
                "12345678",
                "12345678",
                false,
                "Demo Comment");

        sponsorRepository.save(sponsor);

        try {
            byte[] pdfBytes = Files.readAllBytes(Paths.get("C:\\Users\\mathi\\Downloads\\easyFIle.pdf"));
            contact.setPdfData(pdfBytes);

            System.out.println("\n \n PDF file loaded successfully! \n \n");
        } catch (Exception e) {
            System.out.println("Could not set PDF data: " + e.getMessage());
        }
        contractRepository.save(contact);
        User user = new User();
        user.setName(name);
        user.setEmail(email);
        userRepository.save(user);
        return "redirect:/users";
    }

    @PostMapping("/login/confirm")
    public String confirmLogin(
            @RequestParam String username,
            @RequestParam String email,
            Model model) {

        User user = userRepository.findByName(username);

        if (user == null || !user.getEmail().equals(email)) {
            model.addAttribute("error", "Invalid username or email");
            return "login";
        }

        model.addAttribute("user", user);
        return "Complete";
    }
}